version: "3.8"

services:
  postgres:
    container_name: postgres-email
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: emailSend
    ports:
      - "5435:5432"
    volumes:
      - postgres_email:/var/lib/postgresql/data
    networks:
      - api-email

  app:
    container_name: api-email
    image: matheusabd/sendemail
    ports:
      - "8080:8080"
    networks:
      - api-email
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/emailSend?createDatabaseIfNotExist=true
      - spring.datasource.username=postgres
      - spring.datasource.password=root
      - spring.mail.username=${EMAIL_USER}
      - spring.mail.password=${EMAIL_SEND}
    depends_on:
      - postgres

volumes:
  postgres_email:

networks:
  api-email: